### ISSUE TITLE
Unable to search Prefixes

### ISSUE THREAD

**Issue by mukulgoyal90** [spokesoftware/aws_cloud_search#19]
Currently, it seems like we can not search with prefixes. For example, if I search "disc*", it should show the results having words like of "discount", it doesn't work. We're able to search by passing the complete word only e.g 'discount'.

Please note that, this prefixes search is possible as per AWS CloudSearch documentations https://docs.aws.amazon.com/cloudsearch/latest/developerguide/searching-compound-queries.html

Any help is much appreciated.

**Comment by javmorin** [comment]
The document you've referenced is for the 2013 API, while this gem only supports the 2011 API and is no longer maintained. For 2013 API support, we recommend using the official aws/aws-sdk-ruby gems. 

If you are using the 2011 API, it is possible to use this gem to do a search as you describe.
The docs are available [here](http://awsdocs.s3.amazonaws.com/cloudsearch/2011-02-01/cloudsearch-dg-2011-02-01.pdf) with the wildcard explanation (needed for prefix searches) on page 90.
